package com.thaihoc.hotelbooking.exception;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
    public enum ErrorCode {
    // ========== USER VALIDATION ==========
    FULL_NAME_REQUIRED(1001, "FULL_NAME_REQUIRED", HttpStatus.BAD_REQUEST),
    EMAIL_REQUIRED(1002, "EMAIL_REQUIRED", HttpStatus.BAD_REQUEST),
    EMAIL_INVALID(1003, "EMAIL_INVALID", HttpStatus.BAD_REQUEST),
    PASSWORD_REQUIRED(1004, "PASSWORD_REQUIRED", HttpStatus.BAD_REQUEST),
    PASSWORD_TOO_SHORT(1005, "PASSWORD_TOO_SHORT", HttpStatus.BAD_REQUEST),
    PHONE_REQUIRED(1006, "PHONE_REQUIRED", HttpStatus.BAD_REQUEST),
    PHONE_INVALID(1007, "PHONE_INVALID", HttpStatus.BAD_REQUEST),
    FULL_NAME_INVALID(1008, "FULL_NAME_INVALID", HttpStatus.BAD_REQUEST),


    // ========== USER BUSINESS LOGIC ==========
    USER_EMAIL_ALREADY_EXISTS(1010, "USER_EMAIL_ALREADY_EXISTS", HttpStatus.CONFLICT),
    USER_PHONE_ALREADY_EXISTS(1011, "USER_PHONE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    USER_CREATION_FAILED(1012, "USER_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    // ========== GENERAL ==========
    USER_INVALID_REQUEST(1100, "USER_INVALID_REQUEST", HttpStatus.BAD_REQUEST),
    UNHANDLED_EXCEPTION(1999, "UNHANDLED_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY(1111,"INVALID_KEY exception", HttpStatus.BAD_REQUEST),

    USER_NOT_FOUND(1013, "USER_NOT_FOUND", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1014, "UNAUTHENTICATED", HttpStatus.BAD_REQUEST),
    UNAUTHORIZE(1015, "UNAUTHORIZE", HttpStatus.UNAUTHORIZED),

    // ========== PERMISSION REQUEST ==========
    PERMISSION_NOT_FOUND(2010, "PERMISSION_NOT_FOUND", HttpStatus.NOT_FOUND),
    PERMISSION_ALREADY_EXISTS(2011, "PERMISSION_ALREADY_EXISTS", HttpStatus.CONFLICT),
    PERMISSION_ASSIGN_FAILED(2012, "PERMISSION_ASSIGN_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    PERMISSION_ACCESS_DENIED(2013, "PERMISSION_ACCESS_DENIED", HttpStatus.FORBIDDEN),

    // ========== ROLE BUSINESS LOGIC ==========
    ROLE_NAME_ALREADY_EXISTS(3010, "ROLE_NAME_ALREADY_EXISTS", HttpStatus.CONFLICT),
    ROLE_CREATION_FAILED(3011, "ROLE_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_NOT_FOUND(3012, "ROLE_NOT_FOUND", HttpStatus.NOT_FOUND),
    ROLE_PERMISSION_INVALID(3013, "ROLE_PERMISSION_INVALID", HttpStatus.BAD_REQUEST),
    ROLE_ASSIGN_FAILED(3014, "ROLE_ASSIGN_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_IN_USE(3015, "ROLE_IN_USE", HttpStatus.CONFLICT),
    ROLE_DELETE_FAILED(3016, "ROLE_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    // ========== BRANCH BUSINESS LOGIC ==========
    BRANCH_NAME_ALREADY_EXISTS(3020, "BRANCH_NAME_ALREADY_EXISTS", HttpStatus.CONFLICT),
    BRANCH_CREATION_FAILED(3021, "BRANCH_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BRANCH_NOT_FOUND(3022, "BRANCH_NOT_FOUND", HttpStatus.NOT_FOUND),
    BRANCH_PERMISSION_INVALID(3023, "BRANCH_PERMISSION_INVALID", HttpStatus.BAD_REQUEST),
    BRANCH_ASSIGN_FAILED(3024, "BRANCH_ASSIGN_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BRANCH_IN_USE(3025, "BRANCH_IN_USE", HttpStatus.CONFLICT),
    BRANCH_DELETE_FAILED(3026, "BRANCH_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),


    // ========== ROOMTYPE BUSINESS LOGIC ==========
    ROOM_TYPE_NAME_ALREADY_EXISTS(3030, "ROOMTYPE_NAME_ALREADY_EXISTS", HttpStatus.CONFLICT),
    ROOM_TYPE_CREATION_FAILED(3031, "ROOMTYPE_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_TYPE_NOT_FOUND(3032, "ROOMTYPE_NOT_FOUND", HttpStatus.NOT_FOUND),
    ROOM_TYPE_UPDATE_FAILED(3033, "ROOMTYPE_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_TYPE_DELETE_FAILED(3034, "ROOMTYPE_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_TYPE_IN_USE(3035, "ROOMTYPE_IN_USE", HttpStatus.CONFLICT),
    ROOM_TYPE_PHOTO_INVALID(3036, "ROOMTYPE_PHOTO_INVALID", HttpStatus.BAD_REQUEST),
    ROOM_TYPE_CAPACITY_INVALID(3037, "ROOMTYPE_CAPACITY_INVALID", HttpStatus.BAD_REQUEST),

    // ========== ROOM PHOTO BUSINESS LOGIC ==========
    ROOM_PHOTO_UPLOAD_FAILED(3040, "ROOM_PHOTO_UPLOAD_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_PHOTO_NOT_FOUND(3041, "ROOM_PHOTO_NOT_FOUND", HttpStatus.NOT_FOUND),
    ROOM_PHOTO_DELETE_FAILED(3042, "ROOM_PHOTO_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_PHOTO_INVALID_FORMAT(3043, "ROOM_PHOTO_INVALID_FORMAT", HttpStatus.BAD_REQUEST),
    ROOM_PHOTO_TOO_LARGE(3044, "ROOM_PHOTO_TOO_LARGE", HttpStatus.BAD_REQUEST),
    ROOM_PHOTO_ALREADY_EXISTS(3045, "ROOM_PHOTO_ALREADY_EXISTS", HttpStatus.CONFLICT),

    // ========== ROOM BUSINESS LOGIC ==========
    ROOM_NUMBER_ALREADY_EXISTS(3050, "ROOM_NUMBER_ALREADY_EXISTS", HttpStatus.CONFLICT),
    ROOM_CREATION_FAILED(3051, "ROOM_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_NOT_FOUND(3052, "ROOM_NOT_FOUND", HttpStatus.NOT_FOUND),
    ROOM_UPDATE_FAILED(3053, "ROOM_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_DELETE_FAILED(3054, "ROOM_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_IN_USE(3055, "ROOM_IN_USE", HttpStatus.CONFLICT),
    ROOM_CAPACITY_INVALID(3056, "ROOM_CAPACITY_INVALID", HttpStatus.BAD_REQUEST),
    ROOM_STATUS_INVALID(3057, "ROOM_STATUS_INVALID", HttpStatus.BAD_REQUEST),
    ROOM_ASSIGN_FAILED(3058, "ROOM_ASSIGN_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),

    // ========== BOOKING TYPE BUSINESS LOGIC ==========
    BOOKING_TYPE_CODE_ALREADY_EXISTS(3060, "BOOKING_TYPE_CODE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    BOOKING_TYPE_NAME_ALREADY_EXISTS(3061, "BOOKING_TYPE_NAME_ALREADY_EXISTS", HttpStatus.CONFLICT),
    BOOKING_TYPE_CREATION_FAILED(3062, "BOOKING_TYPE_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_TYPE_NOT_FOUND(3063, "BOOKING_TYPE_NOT_FOUND", HttpStatus.NOT_FOUND),
    BOOKING_TYPE_UPDATE_FAILED(3064, "BOOKING_TYPE_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_TYPE_DELETE_FAILED(3065, "BOOKING_TYPE_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_TYPE_RULES_INVALID(3066, "BOOKING_TYPE_RULES_INVALID", HttpStatus.BAD_REQUEST),
    BOOKING_TYPE_DURATION_INVALID(3067, "BOOKING_TYPE_DURATION_INVALID", HttpStatus.BAD_REQUEST),
    BOOKING_TYPE_STATUS_INVALID(3068, "BOOKING_TYPE_STATUS_INVALID", HttpStatus.BAD_REQUEST),


    // ========== ROOM TYPE BOOKING TYPE PRICE BUSINESS LOGIC ==========
    ROOM_TYPE_BOOKING_TYPE_PRICE_ALREADY_EXISTS(3070, "ROOM_TYPE_BOOKING_TYPE_PRICE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    ROOM_TYPE_BOOKING_TYPE_PRICE_CREATION_FAILED(3071, "ROOM_TYPE_BOOKING_TYPE_PRICE_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_TYPE_BOOKING_TYPE_PRICE_NOT_FOUND(3072, "ROOM_TYPE_BOOKING_TYPE_PRICE_NOT_FOUND", HttpStatus.NOT_FOUND),
    ROOM_TYPE_BOOKING_TYPE_PRICE_UPDATE_FAILED(3073, "ROOM_TYPE_BOOKING_TYPE_PRICE_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_TYPE_BOOKING_TYPE_PRICE_DELETE_FAILED(3074, "ROOM_TYPE_BOOKING_TYPE_PRICE_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_TYPE_BOOKING_TYPE_PRICE_INVALID_VALUE(3075, "ROOM_TYPE_BOOKING_TYPE_PRICE_INVALID_VALUE", HttpStatus.BAD_REQUEST),
    ROOM_TYPE_BOOKING_TYPE_PRICE_INACTIVE(3076, "ROOM_TYPE_BOOKING_TYPE_PRICE_INACTIVE", HttpStatus.CONFLICT),
    ROOM_TYPE_BOOKING_TYPE_PRICE_DUPLICATE_DATE(3077, "ROOM_TYPE_BOOKING_TYPE_PRICE_DUPLICATE_DATE", HttpStatus.CONFLICT),


    // ========== BOOKING BUSINESS LOGIC ==========
    BOOKING_CREATION_FAILED(3080, "BOOKING_CREATION_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_NOT_FOUND(3081, "BOOKING_NOT_FOUND", HttpStatus.NOT_FOUND),
    BOOKING_UPDATE_FAILED(3082, "BOOKING_UPDATE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_DELETE_FAILED(3083, "BOOKING_DELETE_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_STATUS_INVALID(3084, "BOOKING_STATUS_INVALID", HttpStatus.BAD_REQUEST),
    BOOKING_DATE_INVALID(3085, "BOOKING_DATE_INVALID", HttpStatus.BAD_REQUEST),
    BOOKING_OVERLAPPING(3086, "BOOKING_OVERLAPPING", HttpStatus.CONFLICT),
    BOOKING_ROOM_NOT_AVAILABLE(3087, "BOOKING_ROOM_NOT_AVAILABLE", HttpStatus.CONFLICT),
    BOOKING_PAYMENT_FAILED(3088, "BOOKING_PAYMENT_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_PAYMENT_REQUIRED(3089, "BOOKING_PAYMENT_REQUIRED", HttpStatus.BAD_REQUEST),
    BOOKING_REFERENCE_ALREADY_EXISTS(3090, "BOOKING_REFERENCE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    BOOKING_CANCEL_FAILED(3091, "BOOKING_CANCEL_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    BOOKING_ALREADY_CANCELLED(3092, "BOOKING_ALREADY_CANCELLED", HttpStatus.CONFLICT),
    BOOKING_GUEST_COUNT_INVALID(3093, "BOOKING_GUEST_COUNT_INVALID", HttpStatus.BAD_REQUEST),
    BOOKING_SOURCE_INVALID(3094, "BOOKING_SOURCE_INVALID", HttpStatus.BAD_REQUEST),
    BOOKING_PAYMENT_METHOD_INVALID(3095, "BOOKING_PAYMENT_METHOD_INVALID", HttpStatus.BAD_REQUEST);

    ;
    ErrorCode(int code, String message, HttpStatusCode httpStatusCode) {
        this.code = code;
        this.message = message;
        this.httpStatusCode = httpStatusCode;
    }

    private int code;
    private String message;
    private HttpStatusCode httpStatusCode;
}
